# Generated by Django 3.2.7 on 2022-05-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
