# Generated by Django 3.2.7 on 2022-04-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220428_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_count', 'title']},
        ),
    ]
