# Generated by Django 4.0.3 on 2022-04-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='order_id',
        ),
    ]
